services:
  node:
    build:
      context: .
    command: npm start
    working_dir: /var/local/src
    environment:
      - NODE_ENV=production
    volumes:
      - .:/var/local/src
    ports:
      - "8011:3000"